pipeline:
  name: Akhand Test Pipeline
  identifier: Akhand_Test_Pipeline
  projectIdentifier: TestProject
  orgIdentifier: RiyaOrg
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            override: false
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Cloud
            spec: {}
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "Build step"
  notificationRules:
    - name: akhand test pipeline notify
      identifier: akhand_test_pipeline_notify
      pipelineEvents:
        - type: PipelineEnd
        - type: StageFailed
          forStages:
            - AllStages
        - type: StageSuccess
          forStages:
            - AllStages
        - type: StageStart
          forStages:
            - AllStages
        - type: StepFailed
          forSteps:
            - AllSteps
      notificationMethod:
        type: Webhook
        spec:
          webhookUrl: https://apszp6.service-now.com/api/sn_devops/v2/devops/tool/orchestration?toolId=b7d7ff02939947907f37f65ea903d696&projectId=8728ff42939947907f37f65ea903d6e9&ni.nolog.token=nqd5fskIj1VprFrNVOYMWqccy7sgDls7
      enabled: true
