pipeline:
  name: Harness Hybrid Pipeline
  identifier: Harness_Hybrid_Pipeline
  projectIdentifier: default_project
  orgIdentifier: default
  tags: {}
  stages:
    - stage:
        name: Build
        identifier: Build
        description: ""
        type: CI
        spec:
          cloneCodebase: false
          caching:
            enabled: true
            override: true
          buildIntelligence:
            enabled: true
          platform:
            os: MacOS
            arch: Amd64
          runtime:
            type: Docker
            spec:
              harnessImageConnectorRef: account.harnessImage
          execution:
            steps:
              - step:
                  type: Run
                  name: Run_1
                  identifier: Run_1
                  spec:
                    shell: Sh
                    command: echo "Build stage"
    - stage:
        name: Test
        identifier: Test
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: ShellScript
                  name: ShellScript_1
                  identifier: ShellScript_1
                  spec:
                    shell: Bash
                    executionTarget: {}
                    source:
                      type: Inline
                      spec:
                        script: sh "Test stage"
                    environmentVariables: []
                    outputVariables: []
                  timeout: 10m
        tags: {}
